<?php

namespace Database\Seeders;

use App\Models\God;
use Illuminate\Database\Seeder;

class GodSeeder extends Seeder
{
    public function run(): void
    {
        $gods = [

            // ── DPS ─────────────────────────────────────────────────────────

            [
                'name'          => 'Thor',
                'domain'        => 'Tonnerre & Combat',
                'archetype'     => 'dps',
                'stat_growth'   => ['hp' => 1, 'atk' => 5, 'def' => 1, 'regen' => 0],
                'passive_skill' => ['type' => 'crit_bonus', 'value' => 15, 'condition' => 'front'],
                'active_skill'  => ['type' => 'aoe_atk', 'multiplier' => 2.0, 'cooldown' => 4],
                'base_hp'       => 22,
                'base_atk'      => 10,
                'base_def'      => 5,
                'base_regen'    => 1,
                'idle_resource' => 'lightning_shard',
                'idle_rate'     => 2,
                'lore'          => 'Fils d\'Odin, il brandit Mjöllnir et fait gronder les cieux. Les géants tremblent à son approche.',
            ],
            [
                'name'          => 'Kali',
                'domain'        => 'Destruction & Temps',
                'archetype'     => 'dps',
                'stat_growth'   => ['hp' => 1, 'atk' => 5, 'def' => 0, 'regen' => 1],
                'passive_skill' => ['type' => 'execute', 'threshold' => 20, 'multiplier' => 2.5],
                'active_skill'  => ['type' => 'multi_strike', 'hits' => 3, 'multiplier' => 0.8, 'cooldown' => 3],
                'base_hp'       => 18,
                'base_atk'      => 11,
                'base_def'      => 4,
                'base_regen'    => 2,
                'idle_resource' => 'blood_crystal',
                'idle_rate'     => 2,
                'lore'          => 'Déesse hindoue de la destruction, elle dévore le temps lui-même et libère le monde de ses illusions.',
            ],
            [
                'name'          => 'Morrigan',
                'domain'        => 'Guerre & Destin',
                'archetype'     => 'dps',
                'stat_growth'   => ['hp' => 1, 'atk' => 4, 'def' => 1, 'regen' => 1],
                'passive_skill' => ['type' => 'lifesteal', 'value' => 10],
                'active_skill'  => ['type' => 'single_atk', 'multiplier' => 2.8, 'cooldown' => 3],
                'base_hp'       => 20,
                'base_atk'      => 9,
                'base_def'      => 5,
                'base_regen'    => 2,
                'idle_resource' => 'blood_crystal',
                'idle_rate'     => 2,
                'lore'          => 'Triple déesse celtique du champ de bataille, elle plane au-dessus des guerriers sous la forme d\'une corneille.',
            ],
            [
                'name'          => 'Tezcatlipoca',
                'domain'        => 'Nuit & Sorcellerie',
                'archetype'     => 'dps',
                'stat_growth'   => ['hp' => 1, 'atk' => 4, 'def' => 1, 'regen' => 1],
                'passive_skill' => ['type' => 'blind', 'chance' => 25, 'duration' => 1],
                'active_skill'  => ['type' => 'curse', 'atk_reduction' => 30, 'duration' => 2, 'cooldown' => 4],
                'base_hp'       => 20,
                'base_atk'      => 10,
                'base_def'      => 5,
                'base_regen'    => 1,
                'idle_resource' => 'shadow_essence',
                'idle_rate'     => 3,
                'lore'          => 'Le Seigneur du miroir fumant aztèque voit tous les péchés des hommes dans son obsidienne et commande la nuit.',
            ],
            [
                'name'          => 'Hermès',
                'domain'        => 'Commerce & Voyages',
                'archetype'     => 'dps',
                'stat_growth'   => ['hp' => 1, 'atk' => 4, 'def' => 1, 'regen' => 1],
                'passive_skill' => ['type' => 'first_strike', 'bonus' => 20],
                'active_skill'  => ['type' => 'speed_boost', 'extra_turns' => 1, 'cooldown' => 5],
                'base_hp'       => 18,
                'base_atk'      => 9,
                'base_def'      => 4,
                'base_regen'    => 2,
                'idle_resource' => 'gold_coin',
                'idle_rate'     => 4,
                'lore'          => 'Messager des dieux, il court plus vite que le vent et rapporte toujours quelque chose au passage.',
            ],

            // ── TANK ────────────────────────────────────────────────────────

            [
                'name'          => 'Zeus',
                'domain'        => 'Ciel & Souveraineté',
                'archetype'     => 'tank',
                'stat_growth'   => ['hp' => 4, 'atk' => 2, 'def' => 3, 'regen' => 1],
                'passive_skill' => ['type' => 'thorns', 'reflect' => 15],
                'active_skill'  => ['type' => 'taunt', 'duration' => 2, 'def_bonus' => 20, 'cooldown' => 4],
                'base_hp'       => 30,
                'base_atk'      => 6,
                'base_def'      => 10,
                'base_regen'    => 2,
                'idle_resource' => 'lightning_shard',
                'idle_rate'     => 3,
                'lore'          => 'Roi de l\'Olympe, maître de la foudre. Sa seule colère peut faire trembler le monde.',
            ],
            [
                'name'          => 'Héphaïstos',
                'domain'        => 'Forge & Feu',
                'archetype'     => 'tank',
                'stat_growth'   => ['hp' => 3, 'atk' => 2, 'def' => 4, 'regen' => 1],
                'passive_skill' => ['type' => 'armor', 'flat_reduction' => 3],
                'active_skill'  => ['type' => 'shield_ally', 'value' => 15, 'target' => 'back', 'cooldown' => 3],
                'base_hp'       => 28,
                'base_atk'      => 6,
                'base_def'      => 11,
                'base_regen'    => 1,
                'idle_resource' => 'iron_ore',
                'idle_rate'     => 3,
                'lore'          => 'Boiteux mais inégalable à l\'enclume, il forge les armes des dieux dans les entrailles des volcans.',
            ],
            [
                'name'          => 'Izanami',
                'domain'        => 'Mort & Création',
                'archetype'     => 'tank',
                'stat_growth'   => ['hp' => 4, 'atk' => 1, 'def' => 3, 'regen' => 2],
                'passive_skill' => ['type' => 'undying', 'hp_threshold' => 10, 'once_per_battle' => true],
                'active_skill'  => ['type' => 'fear', 'chance' => 40, 'skip_turns' => 1, 'cooldown' => 4],
                'base_hp'       => 32,
                'base_atk'      => 5,
                'base_def'      => 10,
                'base_regen'    => 1,
                'idle_resource' => 'soul_fragment',
                'idle_rate'     => 2,
                'lore'          => 'Déesse japonaise de la création et de la mort, reine du Yomi, le pays des ombres.',
            ],
            [
                'name'          => 'Shiva',
                'domain'        => 'Destruction & Renaissance',
                'archetype'     => 'tank',
                'stat_growth'   => ['hp' => 3, 'atk' => 3, 'def' => 3, 'regen' => 1],
                'passive_skill' => ['type' => 'rebirth', 'regen_bonus' => 5, 'on_tier_up' => true],
                'active_skill'  => ['type' => 'aoe_atk', 'multiplier' => 1.5, 'self_dmg' => 5, 'cooldown' => 3],
                'base_hp'       => 28,
                'base_atk'      => 7,
                'base_def'      => 9,
                'base_regen'    => 2,
                'idle_resource' => 'ash_dust',
                'idle_rate'     => 3,
                'lore'          => 'Le Destructeur hindou danse la Tandava pour mettre fin à un cycle cosmique et en commencer un nouveau.',
            ],

            // ── SUPPORT ─────────────────────────────────────────────────────

            [
                'name'          => 'Athéna',
                'domain'        => 'Sagesse & Stratégie',
                'archetype'     => 'support',
                'stat_growth'   => ['hp' => 2, 'atk' => 1, 'def' => 3, 'regen' => 2],
                'passive_skill' => ['type' => 'def_aura', 'value' => 3, 'condition' => 'mid'],
                'active_skill'  => ['type' => 'shield', 'target' => 'ally_lowest_hp', 'value' => 12, 'cooldown' => 3],
                'base_hp'       => 22,
                'base_atk'      => 5,
                'base_def'      => 9,
                'base_regen'    => 3,
                'idle_resource' => 'knowledge_scroll',
                'idle_rate'     => 2,
                'lore'          => 'Déesse de la sagesse née tout armée du crâne de Zeus, elle ne perd jamais une bataille qu\'elle a planifiée.',
            ],
            [
                'name'          => 'Déméter',
                'domain'        => 'Agriculture & Moissons',
                'archetype'     => 'support',
                'stat_growth'   => ['hp' => 2, 'atk' => 0, 'def' => 2, 'regen' => 4],
                'passive_skill' => ['type' => 'regen_aura', 'value' => 2, 'target' => 'all_allies'],
                'active_skill'  => ['type' => 'heal', 'target' => 'ally_lowest_hp', 'value' => 18, 'cooldown' => 3],
                'base_hp'       => 22,
                'base_atk'      => 4,
                'base_def'      => 7,
                'base_regen'    => 4,
                'idle_resource' => 'grain',
                'idle_rate'     => 5,
                'lore'          => 'Mère des récoltes, sa simple présence fait pousser le blé deux fois plus vite.',
            ],
            [
                'name'          => 'Amaterasu',
                'domain'        => 'Soleil & Harmonie',
                'archetype'     => 'support',
                'stat_growth'   => ['hp' => 2, 'atk' => 1, 'def' => 2, 'regen' => 3],
                'passive_skill' => ['type' => 'cleanse', 'chance' => 30, 'on_regen' => true],
                'active_skill'  => ['type' => 'revive', 'target' => 'ally_dead', 'hp_percent' => 25, 'cooldown' => 6],
                'base_hp'       => 24,
                'base_atk'      => 5,
                'base_def'      => 8,
                'base_regen'    => 4,
                'idle_resource' => 'solar_essence',
                'idle_rate'     => 4,
                'lore'          => 'Grande déesse solaire du panthéon shinto, sa lumière chasse les ténèbres et ramène la paix sur la terre des dieux.',
            ],
            [
                'name'          => 'Bastet',
                'domain'        => 'Foyers & Protection',
                'archetype'     => 'support',
                'stat_growth'   => ['hp' => 2, 'atk' => 1, 'def' => 2, 'regen' => 3],
                'passive_skill' => ['type' => 'dodge_aura', 'value' => 10, 'target' => 'all_allies'],
                'active_skill'  => ['type' => 'atk_buff', 'target' => 'ally_highest_atk', 'value' => 20, 'duration' => 2, 'cooldown' => 3],
                'base_hp'       => 22,
                'base_atk'      => 5,
                'base_def'      => 8,
                'base_regen'    => 3,
                'idle_resource' => 'herb',
                'idle_rate'     => 3,
                'lore'          => 'Déesse-chatte égyptienne, gardienne des foyers et protectrice des familles.',
            ],
            [
                'name'          => 'Njörðr',
                'domain'        => 'Mer & Pêche',
                'archetype'     => 'support',
                'stat_growth'   => ['hp' => 2, 'atk' => 1, 'def' => 2, 'regen' => 3],
                'passive_skill' => ['type' => 'idle_boost', 'value' => 20, 'condition' => 'at_base'],
                'active_skill'  => ['type' => 'resource_burst', 'resource' => 'fish', 'value' => 5, 'cooldown' => 5],
                'base_hp'       => 22,
                'base_atk'      => 4,
                'base_def'      => 7,
                'base_regen'    => 4,
                'idle_resource' => 'fish',
                'idle_rate'     => 5,
                'lore'          => 'Dieu vanir des vents et de la mer, maître des pêcheurs et des marins scandinaves.',
            ],

            // ── HYBRID ──────────────────────────────────────────────────────

            [
                'name'          => 'Odin',
                'domain'        => 'Sagesse & Guerre',
                'archetype'     => 'hybrid',
                'stat_growth'   => ['hp' => 2, 'atk' => 3, 'def' => 2, 'regen' => 1],
                'passive_skill' => ['type' => 'knowledge', 'crit_bonus' => 10, 'def_bonus' => 5],
                'active_skill'  => ['type' => 'sacrifice', 'self_hp_cost' => 10, 'ally_atk_buff' => 30, 'duration' => 2, 'cooldown' => 4],
                'base_hp'       => 24,
                'base_atk'      => 8,
                'base_def'      => 7,
                'base_regen'    => 2,
                'idle_resource' => 'knowledge_scroll',
                'idle_rate'     => 3,
                'lore'          => 'Le Tout-Père nordique a sacrifié un œil pour boire à la fontaine de sagesse. Il voit tout, sait tout, prépare Ragnarök.',
            ],
            [
                'name'          => 'Râ',
                'domain'        => 'Soleil & Création',
                'archetype'     => 'hybrid',
                'stat_growth'   => ['hp' => 2, 'atk' => 3, 'def' => 2, 'regen' => 1],
                'passive_skill' => ['type' => 'solar_charge', 'stack_per_turn' => 5, 'max_stacks' => 3],
                'active_skill'  => ['type' => 'solar_burst', 'multiplier' => 1.5, 'bonus_per_stack' => 0.5, 'cooldown' => 4],
                'base_hp'       => 24,
                'base_atk'      => 8,
                'base_def'      => 7,
                'base_regen'    => 2,
                'idle_resource' => 'solar_essence',
                'idle_rate'     => 4,
                'lore'          => 'Dieu solaire suprême d\'Égypte, il traverse le ciel chaque jour dans sa barque de feu et combat Apophis chaque nuit.',
            ],
            [
                'name'          => 'Anubis',
                'domain'        => 'Mort & Jugement',
                'archetype'     => 'hybrid',
                'stat_growth'   => ['hp' => 2, 'atk' => 3, 'def' => 2, 'regen' => 1],
                'passive_skill' => ['type' => 'soul_harvest', 'hp_on_kill' => 8],
                'active_skill'  => ['type' => 'judgment', 'dmg_multiplier' => 2.0, 'bonus_vs_debuffed' => 1.5, 'cooldown' => 4],
                'base_hp'       => 24,
                'base_atk'      => 8,
                'base_def'      => 7,
                'base_regen'    => 1,
                'idle_resource' => 'soul_fragment',
                'idle_rate'     => 3,
                'lore'          => 'Gardien des morts à tête de chacal, il pèse les âmes sur sa balance avant de les juger.',
            ],
            [
                'name'          => 'Quetzalcóatl',
                'domain'        => 'Vent & Connaissance',
                'archetype'     => 'hybrid',
                'stat_growth'   => ['hp' => 2, 'atk' => 2, 'def' => 2, 'regen' => 2],
                'passive_skill' => ['type' => 'wind_step', 'dodge_chance' => 15],
                'active_skill'  => ['type' => 'inspire', 'target' => 'all_allies', 'atk_bonus' => 10, 'regen_bonus' => 2, 'duration' => 2, 'cooldown' => 5],
                'base_hp'       => 22,
                'base_atk'      => 7,
                'base_def'      => 7,
                'base_regen'    => 3,
                'idle_resource' => 'feather',
                'idle_rate'     => 3,
                'lore'          => 'Le Serpent à Plumes aztèque apporte le vent, la sagesse et les arts à l\'humanité.',
            ],
            [
                'name'          => 'Loki',
                'domain'        => 'Ruse & Illusions',
                'archetype'     => 'hybrid',
                'stat_growth'   => ['hp' => 1, 'atk' => 3, 'def' => 2, 'regen' => 2],
                'passive_skill' => ['type' => 'mirror', 'reflect_debuff_chance' => 20],
                'active_skill'  => ['type' => 'swap', 'swap_atk_def' => true, 'target' => 'enemy', 'duration' => 2, 'cooldown' => 4],
                'base_hp'       => 20,
                'base_atk'      => 8,
                'base_def'      => 6,
                'base_regen'    => 2,
                'idle_resource' => 'shadow_essence',
                'idle_rate'     => 3,
                'lore'          => 'Dieu nordique de la ruse, capable de changer de forme et de semer le chaos avec un sourire.',
            ],
            [
                'name'          => 'Xipe Totec',
                'domain'        => 'Saisons & Renouveau',
                'archetype'     => 'hybrid',
                'stat_growth'   => ['hp' => 2, 'atk' => 2, 'def' => 2, 'regen' => 2],
                'passive_skill' => ['type' => 'renewal', 'regen_on_tier_up' => 10],
                'active_skill'  => ['type' => 'shed', 'remove_debuffs' => true, 'heal' => 8, 'cooldown' => 4],
                'base_hp'       => 22,
                'base_atk'      => 7,
                'base_def'      => 7,
                'base_regen'    => 3,
                'idle_resource' => 'seed',
                'idle_rate'     => 4,
                'lore'          => 'Divinité aztèque du renouveau, il se dépouille de sa peau pour que la nature renaisse chaque printemps.',
            ],
        ];

        foreach ($gods as $god) {
            God::create($god);
        }
    }
}